/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as OmniRouteImport } from './routes/omni'
import { Route as PdfToTextRouteImport } from './routes/pdf-to-text'
import { Route as SplitRouteImport } from './routes/split'
import { Route as ViewerRouteImport } from './routes/viewer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const OmniRoute = OmniRouteImport.update({
  id: '/omni',
  path: '/omni',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToTextRoute = PdfToTextRouteImport.update({
  id: '/pdf-to-text',
  path: '/pdf-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge': typeof MergeRoute
  '/omni': typeof OmniRoute
  '/pdf-to-text': typeof PdfToTextRoute
  '/split': typeof SplitRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge': typeof MergeRoute
  '/omni': typeof OmniRoute
  '/pdf-to-text': typeof PdfToTextRoute
  '/split': typeof SplitRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge': typeof MergeRoute
  '/omni': typeof OmniRoute
  '/pdf-to-text': typeof PdfToTextRoute
  '/split': typeof SplitRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/image-to-pdf'
    | '/merge'
    | '/omni'
    | '/pdf-to-text'
    | '/split'
    | '/viewer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/image-to-pdf'
    | '/merge'
    | '/omni'
    | '/pdf-to-text'
    | '/split'
    | '/viewer'
  id:
    | '__root__'
    | '/'
    | '/image-to-pdf'
    | '/merge'
    | '/omni'
    | '/pdf-to-text'
    | '/split'
    | '/viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  MergeRoute: typeof MergeRoute
  OmniRoute: typeof OmniRoute
  PdfToTextRoute: typeof PdfToTextRoute
  SplitRoute: typeof SplitRoute
  ViewerRoute: typeof ViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omni': {
      id: '/omni'
      path: '/omni'
      fullPath: '/omni'
      preLoaderRoute: typeof OmniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-text': {
      id: '/pdf-to-text'
      path: '/pdf-to-text'
      fullPath: '/pdf-to-text'
      preLoaderRoute: typeof PdfToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  MergeRoute: MergeRoute,
  OmniRoute: OmniRoute,
  PdfToTextRoute: PdfToTextRoute,
  SplitRoute: SplitRoute,
  ViewerRoute: ViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
